### ISSUE TITLE
Broke connection to klipper

### ISSUE THREAD

**Issue by themaluxis** [Anonoei/klipper_auto_speed#2]
Hello there, just installed it following your process; It looks like to break my Klipper / Moonraker liaison 

`Internal error during connect: invalid syntax (auto_speed.py, line 91)

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted`

Any idea ?

**Comment by Anonoei** [comment]
@themaluxis could you share your klippy.log file?
