### ISSUE TITLE
[BUG] Autospeed cfg defaults have parsing errors

### ISSUE THREAD

**Issue by tastyratz** [Anonoei/klipper_auto_speed#7]
**Describe the bug**

If I try and paste the autospeed defaults into an autospeed.cfg file to include as shown on the main page Mainsail will not initialize with errors it cannot parse lines in the content.
To resolve, I commented out both
Validate_margin
and
settling_home

Doing so allowed the printer to initialize.
This should be edited to include values that can be parsed in the example or those lines commented out

**Comment by Anonoei** [comment]
Should be fixed in [latest release](https://github.com/Anonoei/klipper_auto_speed/releases/tag/v0.3.3)
